package com.example.account_ledger_core.domain;
public enum ErrorCode {
    DUPLICATE_EVENT_ID, INVALID_EVENT_ORDER, INSUFFICIENT_AVAILABLE_BALANCE,
    SETTLEMENT_AUTH_NOT_FOUND, SETTLEMENT_AUTH_NOT_APPROVED, ACCOUNT_MISMATCH,
    CURRENCY_MISMATCH, EVENT_NOT_FOUND, EVENT_ALREADY_REVERSED, INVALID_REVERSAL_TARGET,
    DUPLICATE_AUTHORIZATION_ID, SETTLEMENT_AMOUNT_INVALID, ACCOUNT_CURRENCY_MISMATCH
}
